<?php
return array(
	'BRAND_IMG_WIDTH' => 100,
	'BRAND_IMG_HEIGHT' => 35,
	// 商品缩略图的大小
	'GOODS_IMG_SM_WIDTH' => 50, 
	'GOODS_IMG_SM_HEIGHT' => 50, 
	'GOODS_IMG_MID_WIDTH' => 130, 
	'GOODS_IMG_MID_HEIGHT' => 130, 
	'GOODS_IMG_BIG_WIDTH' => 350, 
	'GOODS_IMG_BIG_HEIGHT' => 350, 
);